language: python
python:
    - 2.7
    - 3.4
matrix:
    allow_failures:
        -
            python: 3.4
sudo: true
before_install:
    - 'sudo add-apt-repository --yes ppa:ondrej/php'
    - 'sudo apt-get update'
    - 'sudo apt-get install php5.6-cli php5.6-mbstring'
    - 'env php -v'
    - 'wget http://hiqdev.com/hidev/hidev.phar -O hidev.phar && chmod a+x hidev.phar'
    - './hidev.phar --version'
    - './hidev.phar travis/before_install'
install:
    - './hidev.phar travis/install'
script:
    - './hidev.phar travis/script'
after_script:
    - './hidev.phar travis/after_script'
