package:
    type:           project
    name:           rewatcher
    title:          Repositories watcher
    headline:       rewatcher
    keywords:       git, repositories, watcher
    description:    |
        Scans directory tree recursively to find unsynced repositories.

plugins:
    hiqdev/hidev-python:   "*@dev"
    hiqdev/hidev-hiqdev:   "*"
