package:
    type:           project
    name:           rewatcher
    title:          Repositories watcher
    headline:       rewatcher
    keywords:       git, repositories, watcher
    description:    |
        Scans directory tree recursively to find unsynced repositories.

require:
    hiqdev/hidev-python:   "*"
    hiqdev/hidev-composer: "*"
    hiqdev/hidev-vendor:   "*"
