package:
    name:           rewatcher
    type:           project
    headline:       rewatcher
    title:          Repositories watcher
    keywords:       git, repositories, watcher
    description:    |
        Scans directory tree recursively to find unsynced repositories.

require:
    hiqdev/hidev-hiqdev: "*"
    hiqdev/hidev-python: "*"
